FROM mcr.microsoft.com/dotnet/aspnet:6.0.11-focal-amd64

ARG VSHARP_RUNNER_ARCHIVE

WORKDIR /usr/src/

ENV \
    # Unset ASPNETCORE_URLS from aspnet base image
    ASPNETCORE_URLS= \
    # Do not generate certificate
    DOTNET_GENERATE_ASPNET_CERTIFICATE=false \
    # Do not show first run text
    DOTNET_NOLOGO=true \
    # SDK version
    DOTNET_SDK_VERSION=6.0.403 \
    # Enable correct mode for dotnet watch (only mode supported in a container)
    DOTNET_USE_POLLING_FILE_WATCHER=true \
    # Skip extraction of XML docs - generally not useful within an image/container - helps performance
    NUGET_XMLDOC_MODE=skip

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        curl \
        git \
        wget \
		unzip \
        nano \
    && rm -rf /var/lib/apt/lists/*

# Install .NET SDK
RUN curl -fSL --output dotnet.tar.gz https://dotnetcli.azureedge.net/dotnet/Sdk/$DOTNET_SDK_VERSION/dotnet-sdk-$DOTNET_SDK_VERSION-linux-x64.tar.gz \
    && dotnet_sha512='779b3e24a889dbb517e5ff5359dab45dd3296160e4cb5592e6e41ea15cbf87279f08405febf07517aa02351f953b603e59648550a096eefcb0a20fdaf03fadde' \
    && echo "$dotnet_sha512  dotnet.tar.gz" | sha512sum -c - \
    && mkdir -p /usr/share/dotnet \
    && tar -oxzf dotnet.tar.gz -C /usr/share/dotnet ./packs ./sdk ./sdk-manifests ./templates ./LICENSE.txt ./ThirdPartyNotices.txt \
    && rm dotnet.tar.gz \
    # Trigger first run experience by running arbitrary cmd
    && dotnet help

# Install VSharp runner

COPY ${VSHARP_RUNNER_ARCHIVE} .

RUN VSHARP_RUNNER_ARCHIVE_NAME="$(find /usr/src -type f -name '*.zip')" \
	&& VSHARP_RUNNER_DIR=vsharp_runner \
	&& mkdir ${VSHARP_RUNNER_DIR} \
	&& unzip ${VSHARP_RUNNER_ARCHIVE_NAME} -d ${VSHARP_RUNNER_DIR} \
	&& rm ${VSHARP_RUNNER_ARCHIVE_NAME}
