name: 'Run tests and publish docker image'

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: vsharp_cli
  DOCKERFILE_PATH: docker/Dockerfile_runner_cli

jobs:
  run_tests:
    uses: ./.github/workflows/integration_tests.yml
  build:
    uses: ./.github/workflows/build_vsharp.yml
  publish-cli-image:
    needs: [run_tests, build]
    runs-on: ubuntu-20.04
    steps:

    - name: Checkout VSharp
      uses: actions/checkout@v3
      with:
        submodules: false

    - name: Download VSharp.Runner binaries
      uses: actions/download-artifact@v3
      with:
        name: runner
        path: ./runner
    
    - name: Zip VSharp.Runner binaries
      run: |
        cd ./runner
        zip -r ${{ github.workspace }}/runner.zip ./*

    - name: Set timezone
      uses: szenius/set-timezone@v1.0
      with:
        timezoneLinux: "Europe/Moscow"

    - name: Get commit short SHA
      run:
        echo "COMMIT_SHORT_SHA="$(git rev-parse --short HEAD)"" >> $GITHUB_ENV

    - name: Set Docker tag
      run:
        echo "DOCKER_TAG="$(date +%Y).$(date +%-m).$(date +%-d)-${{ env.COMMIT_SHORT_SHA }}"" >> $GITHUB_ENV

    - name: Log in to the Container registry
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: ${{ env.REGISTRY }}/${{ github.repository }}/${{ env.IMAGE_NAME }}
        tags: |
          type=raw,value=${{ env.DOCKER_TAG }}
      
    - name: Docker Buildx (build and push)
      run: |
        docker buildx build \
          -f ${{ env.DOCKERFILE_PATH }} \
          --cache-from "type=local,src=/tmp/.buildx-cache" \
          --cache-to "type=local,dest=/tmp/.buildx-cache-new" \
          --tag ${{ steps.meta.outputs.tags }} \
          --build-arg VSHARP_RUNNER_ARCHIVE=runner.zip \
          --push .
      
    # Temp fix
    # https://github.com/docker/build-push-action/issues/252
    # https://github.com/moby/buildkit/issues/1896
    - name: Move cache
      run: |
        rm -rf /tmp/.buildx-cache
        mv /tmp/.buildx-cache-new /tmp/.buildx-cache
